name: todo_app
description: Todo app using clean architecture.


publish_to: 'none'













version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'







dependencies:
  flutter:
    sdk: flutter




  cupertino_icons: ^1.0.2
  bloc:
  flutter_bloc:
  firebase_core:
  firebase_auth:
  cloud_firestore:
  equatable:
  email_validator:

dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^2.0.0





flutter:


  uses-material-design: true































